/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.d_1;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author hastr
 */
public class p2_notdefteri extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(p2_notdefteri.class.getName());

    /**
     * Creates new form p2_notdefteri
     */
    public p2_notdefteri() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNot = new javax.swing.JScrollPane();
        txtNotd = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu1 = new javax.swing.JMenu();
        btnOlustur = new javax.swing.JMenuItem();
        btnKaydet = new javax.swing.JMenuItem();
        btnAc = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNotd.setColumns(20);
        txtNotd.setRows(5);
        txtNot.setViewportView(txtNotd);

        menu1.setText("Seçenekler");

        btnOlustur.setText("Yeni Sayfa");
        btnOlustur.addActionListener(this::btnOlusturActionPerformed);
        menu1.add(btnOlustur);

        btnKaydet.setText("Kaydet");
        btnKaydet.addActionListener(this::btnKaydetActionPerformed);
        menu1.add(btnKaydet);

        btnAc.setText("Aç");
        btnAc.addActionListener(this::btnAcActionPerformed);
        menu1.add(btnAc);

        jMenuBar1.add(menu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNot, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNot, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOlusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOlusturActionPerformed
        txtNotd.setText("");
    }//GEN-LAST:event_btnOlusturActionPerformed

    private void btnKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaydetActionPerformed
        JFileChooser file = new JFileChooser();
        String kytNot = txtNotd.getText();

        int sonuc = file.showSaveDialog(this);

        if (sonuc == JFileChooser.APPROVE_OPTION) {
            File fileToSave = file.getSelectedFile();

            String filePath = fileToSave.getAbsolutePath();
            if (!filePath.toLowerCase().endsWith(".txt")) {
                fileToSave = new File(filePath + ".txt");
            }

            try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileToSave))) {
                writer.write(txtNotd.getText());
                JOptionPane.showMessageDialog(this, "Kayıt Tamamlandı");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Dosya kaydedilirken hata oluştu: " + e.getMessage(),
                        "Hata", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnKaydetActionPerformed

    private void btnAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcActionPerformed
        JFileChooser file = new JFileChooser();

        int sonuc = file.showOpenDialog(this);
        if (sonuc == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();

            try (BufferedReader reader = new BufferedReader(new FileReader(selectedFile))) {
                txtNotd.setText("");
                String satir, tumYazi = "";

                while ((satir = reader.readLine()) != null) {
                    tumYazi = tumYazi + satir + "\n";
                }
                txtNotd.setText(tumYazi);

                JOptionPane.showMessageDialog(this, "Dosya başarıyla yüklendi!");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Dosya okunurken bir hata oluştu: " + e.getMessage(),
                        "Hata", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new p2_notdefteri().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAc;
    private javax.swing.JMenuItem btnKaydet;
    private javax.swing.JMenuItem btnOlustur;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menu1;
    private javax.swing.JScrollPane txtNot;
    private javax.swing.JTextArea txtNotd;
    // End of variables declaration//GEN-END:variables
}
