/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.d_1;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hastr
 */
public class p3_ogrencisistem extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(p3_ogrencisistem.class.getName());

    public static class Ogrenci {

        private String ogrNo;
        private String ogrAd;
        private String ogrSoyad;

        //Constructor
        public Ogrenci(String ogrNo, String ogrAd, String ogrSoyad) {
            this.ogrNo = ogrNo;
            this.ogrAd = ogrAd;
            this.ogrSoyad = ogrSoyad;
        }

        //Get-Set kısmı
        public String getNumara() {
            return ogrNo;
        }

        public void setNumara(String ogrNo) {
            this.ogrNo = ogrNo;
        }

        public String getAd() {
            return ogrAd;
        }

        public void setAd(String ogrAd) {
            this.ogrAd = ogrAd;
        }

        public String getSoyad() {
            return ogrSoyad;
        }

        public void setSoyad(String ogrSoyad) {
            this.ogrSoyad = ogrSoyad;
        }

        public String metneCevir() {
            return ogrNo + ";" + ogrAd + ";" + ogrSoyad;
        }

        public static Ogrenci fromFileString(String line) {
            String[] parcalar = line.split(";");
            if (parcalar.length == 3) {
                String ogrNo = parcalar[0];
                String ogrAd = parcalar[1];
                String ogrSoyad = parcalar[2];
                return new Ogrenci(ogrNo, ogrAd, ogrSoyad);
            }
            return null;
        }
    }

    private ArrayList<Ogrenci> ogrenciListesi = new ArrayList<>();
    private DefaultTableModel tabloModeli;

    public p3_ogrencisistem() {
        initComponents();

        listeKur();
    }

    public final void listeKur() {
        tabloModeli = new DefaultTableModel();
        tabloModeli.setColumnIdentifiers(new Object[]{"Numara", "Ad", "Soyad", "Bölüm"});
        tblList.setModel(tabloModeli);
    }

    private void tabloGuncelle(ArrayList<Ogrenci> liste) {
        tabloModeli.setRowCount(0); // Tabloyu temizle
        for (Ogrenci ogr : liste) {
            tabloModeli.addRow(new Object[]{
                ogr.getNumara(),
                ogr.getAd(),
                ogr.getSoyad(),});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();
        txtAd = new javax.swing.JTextField();
        btnEkle = new javax.swing.JButton();
        txtSoyad = new javax.swing.JTextField();
        txtNumara = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSil = new javax.swing.JButton();
        btnGuncelle = new javax.swing.JButton();
        txtArama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblList);

        btnEkle.setText("Ekle");
        btnEkle.addActionListener(this::btnEkleActionPerformed);

        jLabel1.setText("İsim:");

        jLabel2.setText("Soyisim:");

        jLabel3.setText("Numara:");

        btnSil.setText("Sil");
        btnSil.addActionListener(this::btnSilActionPerformed);

        btnGuncelle.setText("Güncelle");
        btnGuncelle.addActionListener(this::btnGuncelleActionPerformed);

        txtArama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAramaKeyReleased(evt);
            }
        });

        jLabel4.setText("Ara:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAd)
                                    .addComponent(txtSoyad)
                                    .addComponent(txtNumara, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnGuncelle, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                    .addComponent(btnEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtArama, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNumara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEkle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuncelle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSil)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtArama, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEkleActionPerformed
        String ogrNo = txtNumara.getText();
        String ogrAd = txtAd.getText();
        String ogrSoyad = txtSoyad.getText();

        if (!ogrNo.isEmpty() && !ogrAd.isEmpty()) {
            Ogrenci yeniOgrenci = new Ogrenci(ogrNo, ogrAd, ogrSoyad);
            ogrenciListesi.add(yeniOgrenci);
            tabloGuncelle(ogrenciListesi);
        } else {
            JOptionPane.showMessageDialog(this, "Hata! Eksik kısımlar mevcut.");
        }
    }//GEN-LAST:event_btnEkleActionPerformed

    private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilActionPerformed
        if (tblList.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Hata! Öğrenci seçilmedi");
        } else {
            ogrenciListesi.remove(tblList.getSelectedRow());
            tabloGuncelle(ogrenciListesi);
        }
    }//GEN-LAST:event_btnSilActionPerformed

    private void btnGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuncelleActionPerformed
        if (tblList.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Hata! Öğrenci seçili değil.");
        } else {
            Ogrenci ogr = ogrenciListesi.get(tblList.getSelectedRow());
            ogr.setNumara(txtNumara.getText().trim());
            ogr.setAd(txtAd.getText().trim());
            ogr.setSoyad(txtSoyad.getText().trim());
            tabloGuncelle(ogrenciListesi);
        }
    }//GEN-LAST:event_btnGuncelleActionPerformed

    private void txtAramaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAramaKeyReleased
        String aranan = txtArama.getText().toLowerCase().trim();
        ArrayList<Ogrenci> filtrelenmisList = new ArrayList<>();

        for (Ogrenci ogr : ogrenciListesi) {
            if (ogr.getAd().toLowerCase().contains(aranan)
                    || ogr.getNumara().toLowerCase().contains(aranan)
                    || ogr.getSoyad().toLowerCase().contains(aranan)) {
                filtrelenmisList.add(ogr);
            }
        }
        tabloGuncelle(filtrelenmisList); 
    }//GEN-LAST:event_txtAramaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new p3_ogrencisistem().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEkle;
    private javax.swing.JButton btnGuncelle;
    private javax.swing.JButton btnSil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblList;
    private javax.swing.JTextField txtAd;
    private javax.swing.JTextField txtArama;
    private javax.swing.JTextField txtNumara;
    private javax.swing.JTextField txtSoyad;
    // End of variables declaration//GEN-END:variables
}
