/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.d_1;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hastr
 */
public class p8_finansprogrami extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(p8_finansprogrami.class.getName());

    /*
    NOT:Uygulama içinde yapılan tüm işlemler "d1\sources\finanstablo.txt" dosyasına kaydedilmektedir.
    */
    
    
    DefaultTableModel model1 = new DefaultTableModel() {
        public boolean tabloDuzenlenebilme(int row, int column) {
            return false;
        }
    };

    public p8_finansprogrami() {
        initComponents();
        tabloKur();
        dosyadanOku();
    }

    public void tabloKur() {
        durumTablo.setModel(model1);
        model1.addColumn("İşlem");
        model1.addColumn("Gelir/Gider");
        model1.addColumn("Miktar");
        cmbGelirGider.removeAllItems();
        cmbGelirGider.addItem("Gelir");
        cmbGelirGider.addItem("Gider");
    }

    public void dosyayaYazdir() {
        try {
            File klasor = new File("sources");
            if (!klasor.exists()) {
                klasor.mkdirs();
            }

            try (BufferedWriter bw = new BufferedWriter(new FileWriter("sources/finanstablo.txt"))) {
                for (int i = 0; i < model1.getRowCount(); i++) {
                    for (int j = 0; j < 3; j++) {
                        Object hucreDegeri = model1.getValueAt(i, j);
                        if (hucreDegeri != null) {
                            bw.write(hucreDegeri.toString());
                        }
                        if (j < 2) {
                            bw.write(" ; ");
                        }
                    }
                    bw.newLine();
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public void dosyadanOku() {
        File dosya = new File("sources/finanstablo.txt");
        if (dosya.exists()) {
            try (BufferedReader br = new BufferedReader(new FileReader(dosya))) {
                String satir;
                while ((satir = br.readLine()) != null) {
                    if (!satir.trim().isEmpty()) {
                        String[] veri = satir.split(" ; ");
                        if (veri.length == 3) {
                            model1.addRow(new Object[]{veri[0], veri[1], veri[2]});
                        }
                    }
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        durumTablo = new javax.swing.JTable();
        lblIslem = new javax.swing.JLabel();
        lblGelirGider = new javax.swing.JLabel();
        lblMiktar = new javax.swing.JLabel();
        txtIslem = new javax.swing.JTextField();
        cmbGelirGider = new javax.swing.JComboBox<>();
        txtMiktar = new javax.swing.JTextField();
        btnEkle = new javax.swing.JButton();
        btnSil = new javax.swing.JButton();
        btnHesapla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        durumTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(durumTablo);

        lblIslem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIslem.setText("İşlem :");

        lblGelirGider.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGelirGider.setText("Gelir/Gider:");

        lblMiktar.setText("Miktar :");

        cmbGelirGider.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnEkle.setText("Ekle");
        btnEkle.addActionListener(this::btnEkleActionPerformed);

        btnSil.setText("Seçili Sil");
        btnSil.addActionListener(this::btnSilActionPerformed);

        btnHesapla.setText("Bütçe Hesapla");
        btnHesapla.addActionListener(this::btnHesaplaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIslem, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIslem, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblMiktar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblGelirGider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbGelirGider, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMiktar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEkle))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHesapla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIslem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIslem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSil, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGelirGider, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbGelirGider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMiktar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMiktar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnHesapla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEkle))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEkleActionPerformed
        try {
            String islem = txtIslem.getText();
            String cesit = (String) cmbGelirGider.getSelectedItem();
            int miktar = Integer.parseInt(txtMiktar.getText());
            String miktarTablo = String.valueOf(miktar);
            model1.addRow(new Object[]{islem, cesit, miktarTablo});
            txtIslem.setText("");
            txtMiktar.setText("");
            dosyayaYazdir();
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Miktar alanına sayı gir!");
        }
    }//GEN-LAST:event_btnEkleActionPerformed

    private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilActionPerformed
        int silinecekIndex = durumTablo.getSelectedRow();
        if (silinecekIndex != -1) {
            model1.removeRow(silinecekIndex);
        } else
            javax.swing.JOptionPane.showMessageDialog(this, "Tablodan işlem seçiniz!");
        dosyayaYazdir();
    }//GEN-LAST:event_btnSilActionPerformed

    private void btnHesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHesaplaActionPerformed
        int toplamButce = 0;
        for (int i = 0; i < model1.getRowCount(); i++) {
            int satirButce = (int) Integer.parseInt((String) model1.getValueAt(i, 2));
            String satirCesit = (String) model1.getValueAt(i, 1);
            if (satirCesit.equals("Gelir")) {
                toplamButce += satirButce;
            } else {
                toplamButce -= satirButce;
            }
        }
        javax.swing.JOptionPane.showMessageDialog(this, "Güncel Bütçe = " + toplamButce);
    }//GEN-LAST:event_btnHesaplaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new p8_finansprogrami().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEkle;
    private javax.swing.JButton btnHesapla;
    private javax.swing.JButton btnSil;
    private javax.swing.JComboBox<String> cmbGelirGider;
    private javax.swing.JTable durumTablo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGelirGider;
    private javax.swing.JLabel lblIslem;
    private javax.swing.JLabel lblMiktar;
    private javax.swing.JTextField txtIslem;
    private javax.swing.JTextField txtMiktar;
    // End of variables declaration//GEN-END:variables
}
